//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocBookSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookInCategories = new HashSet<BookInCategory>();
            this.BookPrices = new HashSet<BookPrice>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int BookID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string AuthorName { get; set; }
        public string Info { get; set; }
        public string Avatar { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> NoOfPublish { get; set; }
        public string PublishTime { get; set; }
        public Nullable<double> BuyPrice { get; set; }
        public Nullable<double> ShowPrice { get; set; }
        public string Tags { get; set; }
        public string ExtendInfo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<BookInCategory> BookInCategories { get; set; }
        public virtual ICollection<BookPrice> BookPrices { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
