//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocBookSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.BookInCategories = new HashSet<BookInCategory>();
        }
    
        public int CateID { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<BookInCategory> BookInCategories { get; set; }
    }
}
