//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocBookSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContraintValue
    {
        public int ContraintID { get; set; }
        public string ContrainName { get; set; }
        public string ContrainDescription { get; set; }
        public string ContrainValue { get; set; }
    }
}
