//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocBookSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CocBookEntities : DbContext
    {
        public CocBookEntities()
            : base("name=CocBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Author> Authors { get; set; }
        public DbSet<Book> Books { get; set; }
        public DbSet<BookInCategory> BookInCategories { get; set; }
        public DbSet<BookPrice> BookPrices { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<ContraintValue> ContraintValues { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<GiftCode> GiftCodes { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<PointTransaction> PointTransactions { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<V_Book> V_Book { get; set; }
        public DbSet<SearchHistory> SearchHistories { get; set; }
        public DbSet<ActivationTicket> ActivationTickets { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
    }
}
